### ISSUE TITLE
Replay game

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-site#32]
Add the option to replay a game move by move

**Comment by rzulian** [comment]
@coyotte508 It seems the inability to replay a game is still present, even with regent game.
https://gaiaform.io/game/strong-island-6215
You can replay until faction selection in server, then nothing else. Locally I've got an error at the first mine build. Can be a map problem? This should be a map with Bope's map

**Comment by coyotte508** [comment]
I think this is fixed
